artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_path: Data/train_FD001.txt
  test_data_path: Data/test_FD001.txt
  rul_data_path: Data/RUL_FD001.txt
  processed_train_path: artifacts/data_ingestion/train_processed.csv
  processed_test_path: artifacts/data_ingestion/test_processed.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks

training:
  root_dir: artifacts/training
  train_data_path: artifacts/data_ingestion/train_processed.csv
  model_path: artifacts/training/model.h5
  feature_columns_path: artifacts/training/feature_columns.json

evaluation:
  root_dir: artifacts/evaluation
  test_data_path: artifacts/data_ingestion/test_processed.csv
  rul_data_path: Data/RUL_FD001.txt
  model_path: artifacts/training/model.h5
  feature_columns_path: artifacts/training/feature_columns.json
  metric_file_path: scores.json
